# Introduction to PyTorch

This notebook serves as a beginning introduction to using PyTorch. The following examples come from the [Pytorch Website](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py).

In [3]:
from __future__ import print_function
import torch

### Working with Tensors

Tensors in Pytorch work similiarly to arrays in __Numpy__.

In [7]:
# A 5x3 uninitialized matrix
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000, -2.0000, -0.0055],
        [-0.0000, -0.0001,  0.0000],
        [-0.0001,  0.0000, -0.0001],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [8]:
# A 5x3 randomly initialized matrix
x = torch.rand(5,3)
print(x)

tensor([[ 0.2146,  0.8339,  0.6487],
        [ 0.9750,  0.4994,  0.7665],
        [ 0.9186,  0.6662,  0.0832],
        [ 0.3927,  0.7331,  0.7665],
        [ 0.0208,  0.9457,  0.8764]])


In [9]:
# A 5x3 Matrix initialized with zeros
x = torch.zeros(5,3)
print(x)

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])


In [10]:
# Initializing a tensor with specified data
x = torch.tensor([[4,2],[51,9]])
print(x)

tensor([[  4,   2],
        [ 51,   9]])


In [12]:
# Creating a tensor based on an existing tensor
x = x.new_ones(5,3, dtype=torch.double)
print(x)
x = torch.randn_like(x)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 1.0838,  1.7098, -0.3133],
        [-2.6345, -0.0226,  0.2006],
        [ 1.1486,  0.2849,  0.4902],
        [-0.1219,  0.2766, -0.4217],
        [-0.1556, -0.0221,  0.8906]], dtype=torch.float64)


In [13]:
# Getting a tensor's size
x.size()

torch.Size([5, 3])